POST http://localhost:8080/api/1/orders
Content-Type: application/json

{
  "productId": 1001,
  "quantity": 1
}

###
POST http://localhost:8080/api/1.0/orders
Content-Type: application/json

{
  "productId": 1001,
  "quantity": 1
}

###
POST http://localhost:8080/api/2/orders
Content-Type: application/json

{
  "productId": 1001,
  "quantity": 1
}

### fail
GET http://localhost:8081/api/products/1?quantity=5

###
GET http://localhost:8081/api/products/1001?quantity=4