spring:
  application:
    name: product
  threads:
    virtual:
      enabled: true
server:
  port: 8081
  mvc:
    problem-details:
      enabled: true
management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0